import { rest } from "msw";

const handlers = [
  rest.get("/api/cells", async (req, res, ctx) => {
    return res(ctx.json(cellsResponse));
  }),
  // rest.post("/checkout", async (req, res, ctx) => {
  //   const user = await users.login(JSON.parse(req.body));
  //   const isAuthorized = user.authorize(req.headers.Authorization);
  //   if (!isAuthorized) {
  //     return res(ctx.status(401), ctx.json({ message: "Not authorized" }));
  //   }
  //   const shoppingCart = JSON.parse(req.body);
  //   // do whatever other things you need to do with this shopping cart
  //   return res(ctx.json({ succes: true }));
  // }),
];
export { handlers };

const cellsResponse = [
  { col: "A", computed: 22, has_ref_error: false, row: 1, value: "22" },
  { col: "A", computed: null, has_ref_error: true, row: 2, value: "=A2" },
  { col: "A", computed: null, has_ref_error: false, row: 3, value: null },
  { col: "A", computed: null, has_ref_error: false, row: 4, value: null },
  { col: "A", computed: null, has_ref_error: false, row: 5, value: null },
  { col: "A", computed: null, has_ref_error: false, row: 6, value: null },
  { col: "A", computed: null, has_ref_error: false, row: 7, value: null },
  { col: "A", computed: null, has_ref_error: false, row: 8, value: null },
  { col: "A", computed: null, has_ref_error: false, row: 9, value: null },
  { col: "A", computed: null, has_ref_error: false, row: 10, value: null },
  { col: "B", computed: null, has_ref_error: false, row: 1, value: null },
  { col: "B", computed: null, has_ref_error: false, row: 2, value: null },
  { col: "B", computed: null, has_ref_error: false, row: 3, value: null },
  { col: "B", computed: null, has_ref_error: false, row: 4, value: null },
  { col: "B", computed: null, has_ref_error: false, row: 5, value: null },
  { col: "B", computed: null, has_ref_error: false, row: 6, value: null },
  { col: "B", computed: null, has_ref_error: false, row: 7, value: null },
  { col: "B", computed: null, has_ref_error: false, row: 8, value: null },
  { col: "B", computed: null, has_ref_error: false, row: 9, value: null },
  { col: "B", computed: null, has_ref_error: false, row: 10, value: null },
  { col: "C", computed: null, has_ref_error: false, row: 1, value: null },
  { col: "C", computed: null, has_ref_error: false, row: 2, value: null },
  { col: "C", computed: null, has_ref_error: false, row: 3, value: null },
  { col: "C", computed: null, has_ref_error: false, row: 4, value: null },
  { col: "C", computed: null, has_ref_error: false, row: 5, value: null },
  { col: "C", computed: null, has_ref_error: false, row: 6, value: null },
  { col: "C", computed: null, has_ref_error: false, row: 7, value: null },
  { col: "C", computed: null, has_ref_error: false, row: 8, value: null },
  { col: "C", computed: null, has_ref_error: false, row: 9, value: null },
  { col: "C", computed: null, has_ref_error: false, row: 10, value: null },
  { col: "D", computed: null, has_ref_error: false, row: 1, value: null },
  { col: "D", computed: null, has_ref_error: false, row: 2, value: null },
  { col: "D", computed: null, has_ref_error: false, row: 3, value: null },
  { col: "D", computed: null, has_ref_error: false, row: 4, value: null },
  { col: "D", computed: null, has_ref_error: false, row: 5, value: null },
  { col: "D", computed: null, has_ref_error: false, row: 6, value: null },
  { col: "D", computed: null, has_ref_error: false, row: 7, value: null },
  { col: "D", computed: null, has_ref_error: false, row: 8, value: null },
  { col: "D", computed: null, has_ref_error: false, row: 9, value: null },
  { col: "D", computed: null, has_ref_error: false, row: 10, value: null },
  { col: "E", computed: null, has_ref_error: false, row: 1, value: null },
  { col: "E", computed: null, has_ref_error: false, row: 2, value: null },
  { col: "E", computed: null, has_ref_error: false, row: 3, value: null },
  { col: "E", computed: null, has_ref_error: false, row: 4, value: null },
  { col: "E", computed: null, has_ref_error: false, row: 5, value: null },
  { col: "E", computed: null, has_ref_error: false, row: 6, value: null },
  { col: "E", computed: null, has_ref_error: false, row: 7, value: null },
  { col: "E", computed: null, has_ref_error: false, row: 8, value: null },
  { col: "E", computed: null, has_ref_error: false, row: 9, value: null },
  { col: "E", computed: null, has_ref_error: false, row: 10, value: null },
  { col: "F", computed: null, has_ref_error: false, row: 1, value: null },
  { col: "F", computed: null, has_ref_error: false, row: 2, value: null },
  { col: "F", computed: null, has_ref_error: false, row: 3, value: null },
  { col: "F", computed: null, has_ref_error: false, row: 4, value: null },
  { col: "F", computed: null, has_ref_error: false, row: 5, value: null },
  { col: "F", computed: null, has_ref_error: false, row: 6, value: null },
  { col: "F", computed: null, has_ref_error: false, row: 7, value: null },
  { col: "F", computed: null, has_ref_error: false, row: 8, value: null },
  { col: "F", computed: null, has_ref_error: false, row: 9, value: null },
  { col: "F", computed: null, has_ref_error: false, row: 10, value: null },
  { col: "G", computed: null, has_ref_error: false, row: 1, value: null },
  { col: "G", computed: null, has_ref_error: false, row: 2, value: null },
  { col: "G", computed: null, has_ref_error: false, row: 3, value: null },
  { col: "G", computed: null, has_ref_error: false, row: 4, value: null },
  { col: "G", computed: null, has_ref_error: false, row: 5, value: null },
  { col: "G", computed: null, has_ref_error: false, row: 6, value: null },
  { col: "G", computed: null, has_ref_error: false, row: 7, value: null },
  { col: "G", computed: null, has_ref_error: false, row: 8, value: null },
  { col: "G", computed: null, has_ref_error: false, row: 9, value: null },
  { col: "G", computed: null, has_ref_error: false, row: 10, value: null },
  { col: "H", computed: null, has_ref_error: false, row: 1, value: null },
  { col: "H", computed: null, has_ref_error: false, row: 2, value: null },
  { col: "H", computed: null, has_ref_error: false, row: 3, value: null },
  { col: "H", computed: null, has_ref_error: false, row: 4, value: null },
  { col: "H", computed: null, has_ref_error: false, row: 5, value: null },
  { col: "H", computed: null, has_ref_error: false, row: 6, value: null },
  { col: "H", computed: null, has_ref_error: false, row: 7, value: null },
  { col: "H", computed: null, has_ref_error: false, row: 8, value: null },
  { col: "H", computed: null, has_ref_error: false, row: 9, value: null },
  { col: "H", computed: null, has_ref_error: false, row: 10, value: null },
  { col: "I", computed: null, has_ref_error: false, row: 1, value: null },
  { col: "I", computed: null, has_ref_error: false, row: 2, value: null },
  { col: "I", computed: null, has_ref_error: false, row: 3, value: null },
  { col: "I", computed: null, has_ref_error: false, row: 4, value: null },
  { col: "I", computed: null, has_ref_error: false, row: 5, value: null },
  { col: "I", computed: null, has_ref_error: false, row: 6, value: null },
  { col: "I", computed: null, has_ref_error: false, row: 7, value: null },
  { col: "I", computed: null, has_ref_error: false, row: 8, value: null },
  { col: "I", computed: null, has_ref_error: false, row: 9, value: null },
  { col: "I", computed: null, has_ref_error: false, row: 10, value: null },
  { col: "J", computed: null, has_ref_error: false, row: 1, value: null },
  { col: "J", computed: null, has_ref_error: false, row: 2, value: null },
  { col: "J", computed: null, has_ref_error: false, row: 3, value: null },
  { col: "J", computed: null, has_ref_error: false, row: 4, value: null },
  { col: "J", computed: null, has_ref_error: false, row: 5, value: null },
  { col: "J", computed: null, has_ref_error: false, row: 6, value: null },
  { col: "J", computed: null, has_ref_error: false, row: 7, value: null },
  { col: "J", computed: null, has_ref_error: false, row: 8, value: null },
  { col: "J", computed: null, has_ref_error: false, row: 9, value: null },
  { col: "J", computed: null, has_ref_error: false, row: 10, value: null },
];
